# Generated by Django 4.2.17 on 2025-11-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reportaccess_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishmentreport',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'First Quarter'), (2, 'Second Quarter'), (3, 'Third Quarter'), (4, 'Fourth Quarter')], default=1, help_text='Quarter number'),
        ),
    ]
